### ISSUE TITLE
请求加个参考链接

### ISSUE THREAD

**Issue by xcatliu** [LucaPeng/eslint-config-mfe#1]
> MFE团队通用ESLint 规范，包含es6、react、vue、node规范。es6规范基于airbnb-base，�react规范基于airbnb，vue规范基于eslint-plugin-vue。
>
> 此外，规范提供了 typescript 支持，�整体结构设计如下

TypeScript 部分是参考了 [eslint-config-alloy](https://github.com/AlloyTeam/eslint-config-alloy/blob/master/typescript.js) 的，请问可以加个链接么？

**Comment by LucaPeng** [comment]
已经在 README 和 具体文件中添加了说明和链接，sorry for that~
